### ISSUE TITLE
Unable to hide header and other stylings

### ISSUE THREAD

**Issue by RupinSahu** [manishjanky/ngx-sortable#7]
Hi Manish, I am unable to hide header and other ui components. Kindly, guide me to hide it and please provide a complete documentation so that I can understand about each and every element variables.

**Comment by JorgeBarcaCWT** [comment]
I added this css to my main css file and everything works:

```scss
ngx-sortable .sortable-container {
  padding: 10px;
  max-height: 350px;
  overflow-y: auto;

  .sortable-header {
    display: none;
  }
  .sortable-list {

    .drop-zone {
      background: rgba($black, 0.3) !important;
      opacity: 0.3 !important;
      border: 2px dotted $black !important;
    }

    li.active {
      background: unset !important;
      color: unset;
    }
    .sortable-list-item {
      white-space: nowrap;
      text-overflow: ellipsis;
      overflow: hidden;
      padding: 4px 0;
      & > i {
        margin-right: 4px;
      }
    }
  }

} 
```

Hope it helps
