### ISSUE TITLE
sortable header is showing by applying none

### ISSUE THREAD

**Issue by VishalMSoni** [manishjanky/ngx-sortable#8]
i don't want to show sortable header how to remove it

**Comment by fendri-x** [comment]
same issue

**Comment by JorgeBarcaCWT** [comment]
```css
ngx-sortable .sortable-container .sortable-header {
    display: none;
}
```
This seems to work just fine when added to the main css file.

Hope it helps!
